### Model
model_name_or_path: /data/public/models/base/Qwen/Qwen3-4B

### Method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05

### Dataset
dataset: qwen3_train_1000
template: qwen3
cutoff_len: 8192
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
val_size: 0.1

### Output
output_dir: /data/private/outputs/qwen3_4b_lora_900samples-reyaml1
logging_dir: /data/private/outputs/qwen3_4b_lora_900samples-reyaml1/logs
logging_steps: 10
save_steps: 50
save_total_limit: 3
overwrite_output_dir: true
report_to: tensorboard

### Training hyperparameters
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 8
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
fp16: true

### Evaluation
eval_strategy: steps
eval_steps: 50
per_device_eval_batch_size: 4

### Optimization
gradient_checkpointing: true
optim: adamw_torch
weight_decay: 0.01
max_grad_norm: 1.0

### Saving
save_strategy: steps
load_best_model_at_end: true
metric_for_best_model: eval_loss

### Other
seed: 42
